services:
  logs-collector:
    container_name: logs-collector
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
